const JET_PROTOCOL_PROGRAM = 'JPLockxtkngHkaQT5AuRYow3HyUv5qWzmhwsCPd653n';
const WORDCEL_PROGRAM_ID = 'EXzAYHZ8xS6QJ6xGRsdKZXixoQBLsuMbmwJozm85jHp';
const JET_REWARDS_PROGRAM = 'JET777rQuPU8BatFbhp6irc1NAbozxTheBqNo25eLQP';
const GEM_BANK_PROGRAM = 'bankHHdqMuaaST4qQk6mkzxGeKPHWmqdgor6Gs8r88m';

module.exports = {
    JET_PROTOCOL_PROGRAM,
    WORDCEL_PROGRAM_ID,
    JET_REWARDS_PROGRAM,
    GEM_BANK_PROGRAM
}